require("packer")

require("config.plugins.lsp")
require("config.plugins.treesitter")
require("config.plugins.luasnip")
require("config.plugins.cmp")
require("config.plugins.autopairs")
require("config.plugins.telescope")
require("config.plugins.bufferline")
require("config.plugins.nvim-tree")
require("config.plugins.toggleterm")
require("config.plugins.spellsitter")
require("config.plugins.comment")
require("config.plugins.notify")
require("config.plugins.fidget")
